; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Feb 23 2022 07:28:13 GMT-0800 (Pacific Standard Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


