; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Feb 23 2022 07:28:14 GMT-0800 (Pacific Standard Time)
M280 P0 S90 ; retract BLTouch

