; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Wed Feb 23 2022 07:28:16 GMT-0800 (Pacific Standard Time)
; Wait for set temperatures to be reached
M116 P0

